#define JOB_RED_SOLDIER "Redistan Soldier"
#define JOB_RED_SAPPER "Redistan Sapper"
#define JOB_RED_SNIPER "Redistan Sniper"
#define JOB_RED_GUNNER "Redistan Gunner"
#define JOB_RED_SQUAD_LEADER "Redistan Officer"
#define JOB_RED_COMMANDER "Redistan Commander"

#define JOB_BLUE_SOLDIER "Blusnian Rifleman"
#define JOB_BLUE_SAPPER "Blusnian Technic"
#define JOB_BLUE_SNIPER "Blusnian Marksman"
#define JOB_BLUE_GUNNER "Blusnian Trooper"
#define JOB_BLUE_SQUAD_LEADER "Blusnian Officer"
#define JOB_BLUE_COMMANDER "Blusnian Captain"

#define JOB_YELLOW_SOLDIER "Yellowsie Soldier"
#define JOB_YELLOW_SAPPER "Yellowsie Sapper"
#define JOB_YELLOW_SNIPER "Yellowsie Sniper"
#define JOB_YELLOW_GUNNER "Yellowsie Gunner"
#define JOB_YELLOW_SQUAD_LEADER "Yellowsie Officer"
#define JOB_YELLOW_COMMANDER "Yellowsie Commander"

#define JOB_GREEN_SOLDIER "Greenland Rifleman"
#define JOB_GREEN_SAPPER "Greenland Technic"
#define JOB_GREEN_SNIPER "Greenland Marksman"
#define JOB_GREEN_GUNNER "Greenland Trooper"
#define JOB_GREEN_SQUAD_LEADER "Greenland Officer"
#define JOB_GREEN_COMMANDER "Greenland Captain"

#define JOB_PARTISAN_SOLDIER "Partisan Militia"
#define JOB_PARTISAN_SAPPER "Partisan Technic"
#define JOB_PARTISAN_SNIPER "Partisan Huntsman"
#define JOB_PARTISAN_GUNNER "Partisan Warrior"
#define JOB_PARTISAN_SQUAD_LEADER "Partisan Goon Leader"
#define JOB_PARTISAN_COMMANDER "Partisan Leader"
