#define JOB_RED_SOLDIER "Redistan Soldier"
#define JOB_RED_SAPPER "Redistan Sapper"
#define JOB_RED_SNIPER "Redistan Sniper"
#define JOB_RED_GUNNER "Redistan Gunner"
#define JOB_RED_SQUAD_LEADER "Redistan Officer"
#define JOB_RED_COMMANDER "Redistan Commander"

#define JOB_BLUE_SOLDIER "Blusnian Rifleman"
#define JOB_BLUE_SAPPER "Blusnian Technic"
#define JOB_BLUE_SNIPER "Blusnian Marksman"
#define JOB_BLUE_GUNNER "Blusnian Trooper"
#define JOB_BLUE_SQUAD_LEADER "Blusnian Officer"
#define JOB_BLUE_COMMANDER "Blusnian Captain"

#define JOB_YELLOW_SOLDIER "Yellowsi Soldier"
#define JOB_YELLOW_SAPPER "Yellowsi Sapper"
#define JOB_YELLOW_SNIPER "Yellowsi Sniper"
#define JOB_YELLOW_GUNNER "Yellowsi Gunner"
#define JOB_YELLOW_SQUAD_LEADER "Yellowsi Officer"
#define JOB_YELLOW_COMMANDER "Yellowsi Commander"

#define JOB_GREEN_SOLDIER "Greenland Rifleman"
#define JOB_GREEN_SAPPER "Greenland Technic"
#define JOB_GREEN_SNIPER "Greenland Marksman"
#define JOB_GREEN_GUNNER "Greenland Trooper"
#define JOB_GREEN_SQUAD_LEADER "Greenland Officer"
#define JOB_GREEN_COMMANDER "Greenland Captain"
